version: 2
jobs:
  test:
    working_directory: ~/nlp
    docker:
      - image: circleci/node:9.6.1-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install --production=false
      - run: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn eslint
      - run: yarn test
